CREATE TABLE division (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    competition_id BIGINT NOT NULL,
    CONSTRAINT fk_division_competition FOREIGN KEY (competition_id) REFERENCES competition(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS division_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    gender VARCHAR(50),
    competition_id BIGINT NOT NULL,
    division_id BIGINT NOT NULL,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'REGISTERED',
    CONSTRAINT fk_participant_competition FOREIGN KEY (competition_id) REFERENCES competition(id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_division FOREIGN KEY (division_id) REFERENCES division(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS participant_seq START WITH 1 INCREMENT BY 1;